# Generated by Django 5.2.4 on 2025-08-14 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_formulaire', models.JSONField()),
                ('client_sage', models.JSONField(blank=True, null=True)),
                ('articles_sage', models.JSONField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('non_validee', 'Non validée'), ('validee', 'Validée')], default='non_validee', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
