# Generated by Django 5.2.4 on 2025-08-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='id_sage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
